---
- hosts: all  # Targets all hosts in the inventory, filtered at runtime
  become: yes
  vars:
    message_size: 1024  # Message size in Bytes [1KB]
    log_file: "/var/log/chatty_messages.log"  # Where messages will be logged on the VM
  tasks:
    - name: Ensure log directory exists
      file:
        path: "/var/log"
        state: directory
        mode: "0755"

    - name: Deploy message generator script
      copy:
        dest: "/usr/local/bin/chatty_generator.py"
        mode: "0755"
        content: |
          #!/usr/bin/env python3
          import time
          import os
          
          message_size = {{ message_size }}
          log_file = "{{ log_file }}"
          message = "$" * message_size
          
          while True:
              with open(log_file, "a") as f:
                  timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
                  f.write(f"{timestamp} - {message}\n")
              time.sleep(1)  # 1-second interval between messages

    - name: Run the message generator in the background
      shell: "nohup /usr/local/bin/chatty_generator.py &"
      args:
        creates: "/usr/local/bin/chatty_generator.py"  # Only runs if script wasn’t already there
      async: 0  # Don’t wait for it to finish
      poll: 0   # Detach immediately
